version: '3.9'
services:
  # Contenedor POSTGRES
  postgres:
    image: postgres:14.4
    container_name: postgresParameta
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - parameta_network

#contendor de la aplicacion
  app:
    build: #  Define como se construye la imagen del contenedor.
      context: ./parameta # Usa el directorio actual como contexto de construccion.
      dockerfile: DockerfIle # Especifica el archivo Dockerfile a utilizar
    container_name: restApiEmployee
    depends_on:
      - postgres 
      - mysql    
    env_file: # Carga variables de entorno desde un archivo .env
      - .env
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - parameta_network
      
  appsoap:
    build: 
      context: ./ws-soap
      dockerfile: DockerfIle 
    container_name: soapEmployee
    depends_on:
      - postgres   
      - mysql  
    env_file: # Carga variables de entorno desde un archivo .env
      - .env
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - parameta_network

# Red personalizada para la comunicacion entre contenedores
networks:
  parameta_network:
    driver: bridge  

# Volumenes para la persistencia de datos
volumes:
  postgres:
