server: 
  port: 8081
  servlet:
    context-path:

spring:
  application:
    name: ws-soap

  datasource:
    url: jdbc:postgresql://localhost:5432/parameta
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
