
package parameta.demo.ws.client.pojo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeePort", targetNamespace = "http://producer-soap:8081/soap/employee")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeePort {


    /**
     * 
     * @param saveEmployeeRequest
     * @return
     *     returns parameta.demo.ws.client.pojo.SaveEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "saveEmployeeResponse", targetNamespace = "http://producer-soap:8081/soap/employee", partName = "saveEmployeeResponse")
    public SaveEmployeeResponse saveEmployee(
        @WebParam(name = "saveEmployeeRequest", targetNamespace = "http://producer-soap:8081/soap/employee", partName = "saveEmployeeRequest")
        SaveEmployeeRequest saveEmployeeRequest);

}
